USE [master]
GO

/****** Object:  Database [ATSHome]    Script Date: 09/12/2014 17:06:57 ******/
CREATE DATABASE [ATSHome] ON  PRIMARY 
( NAME = N'ATSHome', FILENAME = N'E:\Database_Home\MSSQL10.ATS_HOME\MSSQL\DATA\ATSHome.mdf' , SIZE = 11072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%)
 LOG ON 
( NAME = N'ATSHome_log', FILENAME = N'E:\Database_Home\MSSQL10.ATS_HOME\MSSQL\DATA\ATSHome_1.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 5%)
GO

ALTER DATABASE [ATSHome] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ATSHome].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ATSHome] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ATSHome] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ATSHome] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ATSHome] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ATSHome] SET ARITHABORT OFF 
GO

ALTER DATABASE [ATSHome] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ATSHome] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ATSHome] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ATSHome] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ATSHome] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ATSHome] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ATSHome] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ATSHome] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ATSHome] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ATSHome] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ATSHome] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ATSHome] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ATSHome] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ATSHome] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ATSHome] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ATSHome] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ATSHome] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ATSHome] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ATSHome] SET  READ_WRITE 
GO

ALTER DATABASE [ATSHome] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ATSHome] SET  MULTI_USER 
GO

ALTER DATABASE [ATSHome] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ATSHome] SET DB_CHAINING OFF 
GO

